VERSION: "inference_demo"
TRAINING_TYPE: 'coarse-fine'

FINE_MODEL_PATH: "/workspace/FLARE25/checkpoint_pth/MR_fine" # The path of the downloaded checkpoint directory.f
CHECK_POINT_NAME: "mr_fine_checkpoint.pth"
COARSE_MODEL_PATH: "/workspace/FLARE25/checkpoint_pth/MR_coarse" # The path of the downloaded checkpoint directory.
COARSE_CHECK_POINT_NAME: "mr_coarse_checkpoint.pth"

DATASET:
  BASE_DIR: 'datasets' # The path of the current project datasets directory.

VAL:
  IS_CROP: False
  TTA: False

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True