BASE: ["preprocess_base.yaml"]

TRAINING_TYPE: 'coarse'
# stage1 - preprocess
MR_DATA_PREPROCESS:
  STAGE: 1

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True
  SAVE_SOFTMAX: False

VERSION: "preprocess_step2_CT"

# final stage
DATASET:
  TRAIN_IMAGE_PATH: 'CT/CT_pet'
  TRAIN_MASK_PATH: 'CT/CT_pet_label'
  IS_ABDOMEN_CROP: False
  COARSE:
    PROPRECESS_PATH: "processed_data/coarse/small_segnet/ct/"
