BASE: ["preprocess_base.yaml"]

# stage1 - preprocess
MR_DATA_PREPROCESS:
  STAGE: 2
  MR_RAW_DATA_PATH: "PET/PET_select/"
  TEMP_MR_RAW_DATA_PATH:  "PET/PET_select_label/" # filter C+Delay data
  DATA_PAIR_PATH: "PET/preprocess_data_pair" # using symlink and rename to save Hard Disk Space. it's recoder source filename and symlink name pair. it's json file path.
  # TEMP_PREPROCESSED_PSUEDO_LABEL_PATH: "MR/Training/PLabel/AMOS_MR_good_spacing-833_tmp_demo" # test
  TEMP_PREPROCESSED_PSUEDO_LABEL_PATH: "PET/train_PET_unlabeled_label_temp" # test
  CT_GT_PATH: "PET_labelsVal/"
  OUTPUT_EACH_CT_LABELS_NUM_STATIC_PATH: 'static_info/label_class_static_demo.csv'
  FILTER_CASE_SAVE_PATH: "static_info/filter_plabel_pet_demo.csv" # save filtered case infos . it's csv file path.
  BAD_CASE_PATH: 'PET/preprocess_data_pair/pet_demo.json' # preprocessed fail case file. it's json file path.
  IS_LLD_REGIS_DATA: False

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True
  SAVE_SOFTMAX: False

VERSION: "preprocess_step2_pet"

# final stage
DATASET:
  # TRAIN_IMAGE_PATH: 'MR/Training/PLabel_image/AMOS_MR_good_spacing-833'
  TRAIN_IMAGE_PATH: PET/PET_select
  TRAIN_MASK_PATH: 'PET/PET_select_label'
  IS_ABDOMEN_CROP: False
  COARSE:
    PROPRECESS_PATH: "processed_data/coarse/small_segnet/PET_stage2"
  FINE:
    PROPRECESS_PATH: "processed_data/fine/small_segnet/PET_stage2"
